# default service type is ClusterIp

apiVersion: v1
kind: Service
metadata:
  name: my-service-cip
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      
