---
#volume without items
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod11
spec:
  containers:
    - name: demo
      image: alpine
      command:
        - sleep
        - "3600"
      envFrom:
        - configMapRef:
            name: game-demo
      volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: game-demo

